import assert from 'node:assert/strict'
import { test } from 'node:test'
import { createLetterStrikeGame } from '../src/game/letterStrike.ts'
import { generateForEnemy, generatePuzzle } from '../src/generator/generate.ts'
import { localLexicalProvider } from '../src/generator/lexicalProvider.ts'
import { mutateCandidate } from '../src/generator/mutate.ts'
import { solvePuzzle } from '../src/generator/solve.ts'
import { validatePuzzle } from '../src/generator/validate.ts'
import { withCompiledMeanings } from '../src/generator/meaningCompiler.ts'
import { createStructuralCandidate, quickOptions } from './generator-fixture.ts'

test('ranked bounded generation and automatic enemy choice reproduce the same seed', () => {
  const first = generateForEnemy('MELANCHOLY', 'ranking-repeat', quickOptions)
  const second = generateForEnemy('MELANCHOLY', 'ranking-repeat', quickOptions)
  assert.deepEqual(second, first)
  assert.equal(first.attempted, 2)
  assert.equal(first.ranked.length, 2)
  for (let index = 1; index < first.ranked.length; index += 1) {
    const previous = first.ranked[index - 1]
    const current = first.ranked[index]
    assert.ok(Number(previous.validation.accepted) >= Number(current.validation.accepted))
    if (previous.validation.accepted === current.validation.accepted) assert.ok(previous.quality.total >= current.quality.total)
  }
  const provider = { ...localLexicalProvider, enemyWords: () => ['MELANCHOLY', 'DESPAIR', 'XERO'] }
  const autoOptions = { ...quickOptions, provider, candidateCount: 1 }
  const auto = generatePuzzle('auto-repeat', autoOptions)
  assert.deepEqual(generatePuzzle('auto-repeat', autoOptions), auto)
  assert.ok(['MELANCHOLY', 'DESPAIR'].includes(auto.enemyWord!))
  assert.ok(auto.enemyRejections.some(enemy => enemy.word === 'XERO'))
  assert.ok(auto.ranked.every(item => item.candidate.encounter.startingTiles.length === 16))
})

test('punctuation and long mutation seeds retain distinct reversible candidate identities', () => {
  const colon = createStructuralCandidate('MELANCHOLY', 'same:seed')
  const dash = createStructuralCandidate('MELANCHOLY', 'same-seed')
  assert.notEqual(colon.id, dash.id)
  assert.equal(decodeURIComponent(colon.id.slice('generated-melancholy-meaning2-'.length)), 'same:seed')
  const suffix = 'identical-suffix-that-is-longer-than-twenty-four-characters'
  const first = mutateCandidate(colon, `first:${suffix}`, { kind: 'tile-swap' })
  const second = mutateCandidate(colon, `second:${suffix}`, { kind: 'tile-swap' })
  assert.notEqual(first.id, second.id)
  assert.notEqual(mutateCandidate(colon, 'same:seed').id, mutateCandidate(colon, 'same-seed').id)
  let descendant = colon
  for (let generation = 0; generation < 12; generation += 1) {
    const previousId = descendant.id
    descendant = mutateCandidate(descendant, `generation:${generation}`, { kind: 'tile-swap' })
    assert.equal(descendant.provenance.parentId, previousId)
    assert.equal(descendant.provenance.rootId, colon.id)
    assert.ok(descendant.id.length < colon.id.length + 30)
  }
})

test('automatic fallback reports aggregate progress and keep zero still recognizes acceptance', () => {
  const progress: number[] = []
  const provider = { ...localLexicalProvider, enemyWords: () => ['MELANCHOLY', 'DESPAIR'] }
  const rejected = generatePuzzle('fallback-progress', {
    ...quickOptions, provider, candidateCount: 1,
    validation: { minimumWinningTurns: 100 },
    onProgress: event => progress.push(event.attempted),
  })
  assert.equal(rejected.attempted, 2)
  assert.deepEqual(progress, [1, 2])
  assert.equal(rejected.ranked.length, 2)
  assert.equal(rejected.acceptedCount, 0)
  const accepted = generatePuzzle('auto-keep-zero', {
    ...quickOptions, provider, candidateCount: 1, keep: 0,
    // This fixed witness tests result suppression, independently of later
    // semantic profiles changing the board generated by the same seed.
    scoringMode: 'legacy-bonuses',
    goal: { archetypes: [], description: 'Review result suppression does not change acceptance.' },
    validation: { minimumWinningTurns: 1, minimumReasonableOpenings: 0, requireSemanticImportance: false,
      minimumIntendedMechanicImportance: 0, maximumCriticalSinglePointLetters: 100,
      maximumPrematureDeadStateRate: 1, requireFamiliarWinningWitness: false },
  })
  assert.equal(accepted.attempted, 1)
  assert.equal(accepted.acceptedCount, 1)
  assert.deepEqual(accepted.accepted, [])
})

test('a parent winning trace is only a proposal when the mutated physical board changes', () => {
  const candidate = createStructuralCandidate('MELANCHOLY', 'construction-test:0')
  const oldIds = candidate.construction.plannedTileIds
  assert.ok(oldIds.length > 0)
  const mutated = structuredClone(candidate.encounter)
  const firstSelection = new Set(oldIds[0])
  mutated.startingTiles = mutated.startingTiles.map(tile => firstSelection.has(tile.id) ? { ...tile, letter: 'Z' } : tile)
  assert.throws(() => createLetterStrikeGame(mutated), /stale/)
  const result = solvePuzzle(withCompiledMeanings(mutated), { maxStates: 0, hintLine: oldIds })
  assert.equal(result.solvable, null)
  assert.deepEqual(result.winningLines, [])
})

test('greedy-trap validation separates absent tradeoffs from unproved observed alternatives', () => {
  const result = generateForEnemy('MELANCHOLY', 'greedy-gate', { ...quickOptions, candidateCount: 1 })
  const ranked = result.ranked[0]
  const candidate = { ...ranked.candidate, goal: { archetypes: ['greedy-trap'] as const, description: 'A declared trap needs evidence.' } }
  const absent = validatePuzzle({ ...candidate, goal: { ...candidate.goal, archetypes: [...candidate.goal.archetypes] } },
    { ...ranked.analysis, greedyTrapStrength: 0 })
  assert.ok(absent.reasons.some(reason => reason.code === 'missing-greedy-tradeoff'))
  const unproved = validatePuzzle({ ...candidate, goal: { ...candidate.goal, archetypes: [...candidate.goal.archetypes] } },
    { ...ranked.analysis, greedyTrapStrength: 0.25, isStrongestImmediateOptimal: null })
  assert.ok(unproved.warnings.some(reason => reason.code === 'greedy-trap-unproved'))
  assert.equal(unproved.reasons.some(reason => reason.code === 'missing-greedy-tradeoff'), false)
})
