import type { PartOfSpeech, SemanticRelation } from '../../src/game/types.ts'

export type ConceptProfile = {
  id: string; enemy: string; definition: string; sense: string; bingo: string; letters: string; refills: string; powers: string[];
  routes: string[][]; roots: string[]; wordOnly: string[]; overrides: Record<string, {sense: string; relation: SemanticRelation; reason: string}>;
  supplemental?: Record<string, { definition: string; lemma: string; partOfSpeech: PartOfSpeech; senseId: string; sourceUrl: string }>;
  review: string; hints: [string,string,string]; family?: string; counterPartOfSpeech?: PartOfSpeech
}

/** Reviewed opposite senses. Strict antonyms match the enemy's word type; family previews declare their counter type. */
export const antonymProfiles: ConceptProfile[] = [
  {
    id: 'dry', enemy: 'DRY', definition: 'lacking water or moisture', sense: 'oewn-dry__3.00.01..',
    bingo: 'HYDRATED', letters: 'HYDRATEDWMPSOGGX', refills: 'AETVINYRAMEOSTUL', powers: [],
    routes: [['HYDRATED'], ['DAMP', 'WATERY'], ['DAMP', 'SOGGY', 'RAINY']],
    roots: ['oewn-wet__3.00.01..', 'oewn-wet__3.00.05..', 'oewn-damp__5.00.00.wet.01',
      'oewn-moist__5.00.00.wet.01', 'oewn-soggy__5.00.00.wet.01', 'oewn-dewy__5.00.00.wet.01',
      'oewn-watery__5.00.02.wet.01', 'oewn-watery__5.00.01.wet.01', 'oewn-humid__5.00.00.wet.01',
      'oewn-rainy__5.00.00.wet.01', 'oewn-sodden__5.00.00.wet.01', 'oewn-waterlogged__5.00.00.wet.01'],
    wordOnly: [], overrides: {},
    supplemental: {
      HYDRATED: { definition: 'Having enough water in the body; not dehydrated.', lemma: 'hydrated', partOfSpeech: 'adjective',
        senseId: 'wiktionary-en:hydrated:adjective:2:85896008', sourceUrl: 'https://en.wiktionary.org/w/index.php?title=hydrated&oldid=85896008' },
      SATURATED: { definition: 'Thoroughly soaked with moisture.', lemma: 'saturated', partOfSpeech: 'adjective',
        senseId: 'wiktionary-en:saturated:adjective:2:92016973', sourceUrl: 'https://en.wiktionary.org/w/index.php?title=saturated&oldid=92016973' },
    },
    review: 'Adjectives containing moisture oppose DRY as lacking moisture. HYDRATED is an adjective, not HYDRATE the verb. DAMP, SOGGY and RAINY retain wetness readings; alcohol and humour readings are not admitted. Comparative adjectives remain adjectives.',
    hints: ['Think of something that has enough water in it.', 'The word is often used when talking about drinking enough water.', 'Eight letters, beginning with H.'],
  },
  {
    id: 'mean', enemy: 'MEAN', definition: 'unkind or malicious towards others', sense: 'oewn-mean__5.00.00.nasty.00',
    bingo: 'COMPASSIONATE', letters: 'COMPASSIONATEKDR', refills: 'BLINWTOESAREHUG', powers: [],
    routes: [['COMPASSIONATE'], ['KIND', 'AMIABLE'], ['KIND', 'NICE', 'WARM']],
    roots: ['oewn-kind__3.00.00..', 'oewn-nice__3.00.00..', 'oewn-nice__5.00.00.polite.00',
      'oewn-warm__3.00.02..', 'oewn-amiable__5.00.00.good-natured.00', 'oewn-amiable__5.00.00.friendly.01',
      'oewn-amicable__3.00.00..', 'oewn-benign__5.00.00.kind.00', 'oewn-gentle__5.00.01.kind.00',
      'oewn-humane__3.00.00..', 'oewn-compassionate__3.00.00..', 'oewn-considerate__3.00.00..',
      'oewn-benevolent__3.01.00..', 'oewn-benevolent__5.00.00.kind.00', 'oewn-generous__3.00.02..',
      'oewn-good__3.00.02..', 'oewn-sweet__5.00.00.lovable.00', 'oewn-friendly__3.00.01..',
      'oewn-friendly__5.00.00.amicable.00', 'oewn-loving__3.00.00..', 'oewn-caring__5.00.00.compassionate.00',
      'oewn-tender__3.00.03..', 'oewn-tender__5.00.00.loving.00',
      'oewn-warmhearted__3.00.00..', 'oewn-sympathetic__5.00.00.kind.00', 'oewn-pleasant__5.00.00.nice.00',
      'oewn-polite__3.00.00..', 'oewn-courteous__5.00.00.polite.00', 'oewn-gracious__5.00.00.kind.00'],
    wordOnly: ['oewn-nice__3.00.00..', 'oewn-good__3.00.02..', 'oewn-sweet__5.00.00.lovable.00'], overrides: {},
    review: 'Kind, considerate descriptions oppose an unkind person. COMPASSIONATE is an adjective; COMPASSION and KINDNESS are nouns and cannot damage this adjective enemy. WARM uses its friendly-person reading, not temperature.',
    hints: ['Think of someone who notices another person’s suffering and cares.', 'It describes a person who feels sympathy and wants to help.', 'Thirteen letters, beginning with C.'],
  },
  {
    id: 'dread-power', enemy: 'DREAD', definition: 'a feeling of fear about what may happen', sense: 'oewn-dread__1.12.00..',
    bingo: 'FEARLESSNESS', letters: 'FEARLESSNESSDOGB', refills: 'VONEIRDEEVTLAIS', powers: ['F', 'L'],
    routes: [['FEARLESSNESS'], ['BOLDNESS', 'DARING'], ['EASE', 'NERVE', 'RELIEF']],
    roots: ['oewn-fearlessness__1.12.00..', 'oewn-fearlessness__1.07.00..', 'oewn-courage__1.07.00..',
      'oewn-bravery__1.07.00..', 'oewn-bravery__1.12.00..', 'oewn-valor__1.07.00..', 'oewn-valour__1.07.00..',
      'oewn-nerve__1.07.00..', 'oewn-guts__1.07.00..', 'oewn-daring__1.07.00..', 'oewn-boldness__1.07.00..',
      'oewn-confidence__1.26.02..', 'oewn-intrepidity__1.07.00..',
      'oewn-ease__1.26.02..', 'oewn-relief__1.12.00..', 'oewn-relief__1.26.00..',
      'oewn-calm__1.07.00..', 'oewn-calmness__1.12.00..', 'oewn-peace__1.12.00..', 'oewn-assurance__1.09.00..'],
    wordOnly: ['oewn-nerve__1.07.00..', 'oewn-guts__1.07.00..', 'oewn-confidence__1.26.02..'],
    overrides: { NERVES: { sense: 'oewn-nerves__1.26.00..', relation: 'similar' as const,
      reason: 'Standalone NERVES ordinarily names anxiety, rather than the courage reading of singular NERVE.' } },
    review: 'Nouns for fearlessness, courage, or freedom from distress oppose the feeling of fear. EASE and RELIEF use their emotional readings; neither a verb nor sculptural relief qualifies. FEARLESSNESS is a noun; FEARLESS and BRAVE are adjectives and do no damage. NERVE means courage, DARING names boldness, VALOR names courage (British VALOUR also counts). The plural NERVES is reviewed separately as anxiety, not mechanically inherited from NERVE.',
    hints: ['Look for a noun meaning the absence of fear.', 'It names a quality, rather than describing a person.', 'Twelve letters, beginning with F. Use both blue tiles.'],
  },
  {
    id: 'eternal-power', enemy: 'ETERNAL', definition: 'lasting forever; without an end in time', sense: 'oewn-eternal__5.00.00.permanent.00',
    bingo: 'IMPERMANENT', letters: 'IMPERMANENTBFLOT', refills: 'FIIBECHRYTUASNO', powers: ['P'],
    routes: [['IMPERMANENT'], ['TEMPORAL', 'FINITE'], ['BRIEF', 'FINITE', 'MORTAL']],
    roots: ['oewn-impermanent__3.00.00..', 'oewn-impermanent__5.00.00.finite.00',
      'oewn-brief__5.00.00.short.02', 'oewn-short__3.00.02..', 'oewn-finite__3.00.00..', 'oewn-mortal__3.00.00..',
      'oewn-temporary__3.00.00..', 'oewn-temporal__5.00.00.impermanent.00', 'oewn-transient__5.00.00.impermanent.00',
      'oewn-ephemeral__5.00.00.impermanent.00', 'oewn-fleeting__5.00.00.short.02', 'oewn-momentary__5.00.00.short.02',
      'oewn-transitory__5.00.00.impermanent.00', 'oewn-passing__5.00.00.impermanent.00'],
    wordOnly: ['oewn-brief__5.00.00.short.02', 'oewn-short__3.00.02..', 'oewn-finite__3.00.00..'], overrides: {},
    review: 'Adjectives with a finite lifespan oppose lasting forever. TEMPORAL uses the source’s explicit not-eternal reading. MORTAL describes a life that ends. Mortality and brevity are nouns, and briefly is an adverb: none can damage ETERNAL. One POWER tile supplies the L absent from IMPERMANENT.',
    hints: ['Think of something that will not last.', 'It is the opposite of permanent.', 'Eleven letters, beginning with I. The blue P covers one missing letter.'],
  },
  {
    id: 'sear-family', enemy: 'SEARS', definition: 'causes plants to wither or dry out in the heat', sense: 'oewn-sear__2.30.02..',
    family: 'add water', counterPartOfSpeech: 'verb',
    bingo: 'IRRIGATES', letters: 'IRRIGATESMBPONKL', refills: 'SUOITAEWHSANYD', powers: ['G'],
    routes: [['IRRIGATES'], ['SPRINKLE', 'WATERS'], ['MIST', 'SOAK', 'WATER']],
    roots: ['oewn-irrigate__2.30.00..', 'oewn-water__2.30.00..', 'oewn-water__2.40.00..',
      'oewn-wet__2.30.00..', 'oewn-soak__2.35.01..', 'oewn-soak__2.30.01..',
      'oewn-moisten__2.30.00..', 'oewn-moisten__2.35.00..', 'oewn-mist__2.35.00..', 'oewn-dampen__2.30.01..', 'oewn-drench__2.30.00..',
      'oewn-douse__2.42.09..', 'oewn-douse__2.30.00..', 'oewn-spray__2.35.03..',
      'oewn-sprinkle__2.30.00..', 'oewn-hydrate__2.30.03..', 'oewn-hydrate__2.30.00..', 'oewn-saturate__2.30.04..'],
    wordOnly: ['oewn-saturate__2.30.04..'], overrides: {},
    supplemental: Object.fromEntries(['DAMP', 'DAMPS', 'DAMPED', 'DAMPING'].map(word => [word, {
      definition: 'Make slightly wet.', lemma: 'damp', partOfSpeech: 'verb' as const,
      senseId: 'wiktionary-en:damp:verb:2:92515406', sourceUrl: 'https://en.wiktionary.org/w/index.php?title=damp&oldid=92515406',
    }])),
    review: 'Enemy and counters are verbs. Only adding water or moisture counters drying plants in the heat. IRRIGATES, WATER, WET and SOAK share this single literal action family. Shade, cooling, shelter and repair are outside it. The noun WATER is not the damaging reading; the verb is.',
    hints: ['Look for another way to say supply water.', 'Farmers do this to fields when rain is not enough.', 'Nine letters, beginning with I. The blue G supplies the second S.'],
  },
  {
    id: 'dirt-family', enemy: 'DIRT', definition: 'unclean matter on a surface', sense: 'oewn-dirt__1.26.00..',
    family: 'clean', counterPartOfSpeech: 'verb',
    bingo: 'STERILISED', letters: 'STERILISEDUWPCBX', refills: 'NSTUEAROLIDAFM', powers: [],
    routes: [['STERILISED'], ['DUST', 'RINSE'], ['DUST', 'WIPE', 'SCRUB']],
    roots: ['oewn-clean__2.35.00..', 'oewn-clean__2.29.00..', 'oewn-cleanse__2.29.00..',
      'oewn-dust__2.35.00..', 'oewn-wipe__2.35.00..', 'oewn-scrub__2.35.00..', 'oewn-scrub__2.29.00..',
      'oewn-rinse__2.35.00..', 'oewn-wash__2.35.00..', 'oewn-wash__2.29.00..', 'oewn-wash__2.30.05..',
      'oewn-swab__2.35.00..', 'oewn-scour__2.35.01..', 'oewn-scour__2.35.00..',
      'oewn-soap__2.29.00..', 'oewn-sweep__2.35.01..', 'oewn-mop__2.35.01..',
      'oewn-sterilise__2.29.01..', 'oewn-sterilize__2.29.01..', 'oewn-sanitise__2.35.00..',
      'oewn-sanitize__2.35.00..', 'oewn-disinfect__2.29.00..'],
    wordOnly: ['oewn-wipe__2.35.00..'], overrides: {},
    review: 'Deliberately crosses word types: DIRT is a noun, and all damaging readings are cleaning verbs. Removing dirt and hygienic cleaning form the one stated family; tidying, beauty, purity as a virtue and covering dirt do not. STERILISED uses the cleaning sense, never the infertility sense. DUST uses remove dust, not sprinkle dust.',
    hints: ['Every answer here is an action that cleans.', 'Think of cleaning equipment so that no germs remain.', 'Ten letters, beginning with S. Use the British spelling.'],
  },
]
